"""add registration profile and trial fields

Revision ID: e8529f373ed4
Revises: 7c787c966613
Create Date: 2026-07-29 16:19:56.622900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8529f373ed4'
down_revision: Union[str, Sequence[str], None] = '7c787c966613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=60), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=2), nullable=True))
    op.add_column('users', sa.Column('trial_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('trial_used', sa.Boolean(), server_default='0', nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'trial_used')
    op.drop_column('users', 'trial_ends_at')
    op.drop_column('users', 'trial_started_at')
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    op.drop_column('users', 'username')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
